// <auto-generated />
using System;
using GarageStack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GarageStack.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604131441_DropRawPayload")]
    partial class DropRawPayload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GarageStack.Core.Models.AppNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDeleted", "CreatedAt");

                    b.ToTable("AppNotifications");
                });

            modelBuilder.Entity("GarageStack.Core.Models.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("P256DhKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("GarageStack.Core.Models.TelemetrySnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("BatteryHeating")
                        .HasColumnType("boolean");

                    b.Property<string>("BatteryHeatingScheduleMode")
                        .HasColumnType("text");

                    b.Property<string>("BatteryHeatingScheduleStartTime")
                        .HasColumnType("text");

                    b.Property<double?>("BatteryVoltage")
                        .HasColumnType("double precision");

                    b.Property<string>("BmsChargeStatus")
                        .HasColumnType("text");

                    b.Property<bool?>("BonnetOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ChargerConnected")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ChargingCableLock")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ChargingLastEndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChargingScheduleEndTime")
                        .HasColumnType("text");

                    b.Property<string>("ChargingScheduleMode")
                        .HasColumnType("text");

                    b.Property<string>("ChargingScheduleStartTime")
                        .HasColumnType("text");

                    b.Property<string>("ChargingType")
                        .HasColumnType("text");

                    b.Property<bool?>("ClimateOn")
                        .HasColumnType("boolean");

                    b.Property<double?>("CurrentJourneyDistance")
                        .HasColumnType("double precision");

                    b.Property<bool?>("DriverDoorOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("DriverWindowOpen")
                        .HasColumnType("boolean");

                    b.Property<double?>("Elevation")
                        .HasColumnType("double precision");

                    b.Property<bool?>("EngineRunning")
                        .HasColumnType("boolean");

                    b.Property<double?>("EvSocPercent")
                        .HasColumnType("double precision");

                    b.Property<double?>("ExteriorTemperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("FuelLevelPercent")
                        .HasColumnType("double precision");

                    b.Property<double?>("FuelRangeKm")
                        .HasColumnType("double precision");

                    b.Property<double?>("Heading")
                        .HasColumnType("double precision");

                    b.Property<int?>("HeatedSeatFrontLeft")
                        .HasColumnType("integer");

                    b.Property<int?>("HeatedSeatFrontRight")
                        .HasColumnType("integer");

                    b.Property<bool?>("HvBatteryActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("HvCurrent")
                        .HasColumnType("double precision");

                    b.Property<double?>("HvPower")
                        .HasColumnType("double precision");

                    b.Property<double?>("HvSocKwh")
                        .HasColumnType("double precision");

                    b.Property<double?>("HvTotalCapacityKwh")
                        .HasColumnType("double precision");

                    b.Property<double?>("HvVoltage")
                        .HasColumnType("double precision");

                    b.Property<double?>("InteriorTemperature")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsCharging")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<double?>("LastChargeEndingPower")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("LastChargeStateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastVehicleStateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<bool?>("LightsDippedBeam")
                        .HasColumnType("boolean");

                    b.Property<bool?>("LightsMainBeam")
                        .HasColumnType("boolean");

                    b.Property<bool?>("LightsSide")
                        .HasColumnType("boolean");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("MileageOfTheDay")
                        .HasColumnType("double precision");

                    b.Property<double?>("MileageSinceLastCharge")
                        .HasColumnType("double precision");

                    b.Property<double?>("ObcCurrent")
                        .HasColumnType("double precision");

                    b.Property<double?>("ObcPowerSinglePhase")
                        .HasColumnType("double precision");

                    b.Property<double?>("ObcPowerThreePhase")
                        .HasColumnType("double precision");

                    b.Property<double?>("ObcVoltage")
                        .HasColumnType("double precision");

                    b.Property<double?>("OdometerKm")
                        .HasColumnType("double precision");

                    b.Property<int?>("OffboardChargerPlugStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("OnboardChargerPlugStatus")
                        .HasColumnType("integer");

                    b.Property<bool?>("PassengerDoorOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PassengerWindowOpen")
                        .HasColumnType("boolean");

                    b.Property<double?>("PowerUsageOfDay")
                        .HasColumnType("double precision");

                    b.Property<double?>("PowerUsageSinceLastCharge")
                        .HasColumnType("double precision");

                    b.Property<string>("RawTopic")
                        .HasColumnType("text");

                    b.Property<bool?>("RearLeftDoorOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RearLeftWindowOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RearRightDoorOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RearRightWindowOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RearWindowDefroster")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RemainingChargingTime")
                        .HasColumnType("integer");

                    b.Property<double?>("RemoteTemperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<bool?>("SunRoofOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("TrunkOpen")
                        .HasColumnType("boolean");

                    b.Property<double?>("TyrePressureFrontLeft")
                        .HasColumnType("double precision");

                    b.Property<double?>("TyrePressureFrontRight")
                        .HasColumnType("double precision");

                    b.Property<double?>("TyrePressureRearLeft")
                        .HasColumnType("double precision");

                    b.Property<double?>("TyrePressureRearRight")
                        .HasColumnType("double precision");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "RawTopic")
                        .HasFilter("\"RawTopic\" IS NOT NULL");

                    b.HasIndex("VehicleId", "RecordedAt");

                    b.HasIndex("VehicleId", "Latitude", "Longitude", "RecordedAt")
                        .HasDatabaseName("IX_TelemetrySnapshots_VehicleId_LatLon_RecordedAt")
                        .HasFilter("\"Latitude\" IS NOT NULL AND \"Longitude\" IS NOT NULL");

                    b.ToTable("TelemetrySnapshots");
                });

            modelBuilder.Entity("GarageStack.Core.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("SaicUser")
                        .HasColumnType("text");

                    b.Property<string>("Series")
                        .HasColumnType("text");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.HasKey("Id");

                    b.HasIndex("Vin")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("GarageStack.Core.Models.TelemetrySnapshot", b =>
                {
                    b.HasOne("GarageStack.Core.Models.Vehicle", "Vehicle")
                        .WithMany("TelemetrySnapshots")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GarageStack.Core.Models.Vehicle", b =>
                {
                    b.Navigation("TelemetrySnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
