// <auto-generated />
using System;
using GarageStack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GarageStack.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520213526_AddPhevFields")]
    partial class AddPhevFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GarageStack.Core.Models.TelemetrySnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("BatteryVoltage")
                        .HasColumnType("double precision");

                    b.Property<bool?>("BonnetOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("ClimateOn")
                        .HasColumnType("boolean");

                    b.Property<bool?>("DriverDoorOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("DriverWindowOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("EngineRunning")
                        .HasColumnType("boolean");

                    b.Property<double?>("EvSocPercent")
                        .HasColumnType("double precision");

                    b.Property<double?>("ExteriorTemperature")
                        .HasColumnType("double precision");

                    b.Property<double?>("FuelLevelPercent")
                        .HasColumnType("double precision");

                    b.Property<double?>("FuelRangeKm")
                        .HasColumnType("double precision");

                    b.Property<double?>("Heading")
                        .HasColumnType("double precision");

                    b.Property<double?>("InteriorTemperature")
                        .HasColumnType("double precision");

                    b.Property<bool?>("IsCharging")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("OdometerKm")
                        .HasColumnType("double precision");

                    b.Property<bool?>("PassengerDoorOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("PassengerWindowOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("RawPayload")
                        .HasColumnType("text");

                    b.Property<string>("RawTopic")
                        .HasColumnType("text");

                    b.Property<bool?>("RearLeftDoorOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RearLeftWindowOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RearRightDoorOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("RearRightWindowOpen")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Speed")
                        .HasColumnType("double precision");

                    b.Property<bool?>("SunRoofOpen")
                        .HasColumnType("boolean");

                    b.Property<bool?>("TrunkOpen")
                        .HasColumnType("boolean");

                    b.Property<double?>("TyrePressureFrontLeft")
                        .HasColumnType("double precision");

                    b.Property<double?>("TyrePressureFrontRight")
                        .HasColumnType("double precision");

                    b.Property<double?>("TyrePressureRearLeft")
                        .HasColumnType("double precision");

                    b.Property<double?>("TyrePressureRearRight")
                        .HasColumnType("double precision");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "RecordedAt");

                    b.ToTable("TelemetrySnapshots");
                });

            modelBuilder.Entity("GarageStack.Core.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Series")
                        .HasColumnType("text");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.HasKey("Id");

                    b.HasIndex("Vin")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("GarageStack.Core.Models.TelemetrySnapshot", b =>
                {
                    b.HasOne("GarageStack.Core.Models.Vehicle", "Vehicle")
                        .WithMany("TelemetrySnapshots")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GarageStack.Core.Models.Vehicle", b =>
                {
                    b.Navigation("TelemetrySnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
