# Internal MQTT broker for GarageStack all-in-one container
listener 1883
allow_anonymous true

persistence true
persistence_location /data/db/mosquitto/

log_dest stdout
log_type error
log_type warning
log_type notice
