<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <UserSecretsId>dotnet-GarageStack.Worker-351fecac-5223-4976-a54e-0bd2d3dd5642</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
    <PackageReference Include="MQTTnet" />
    <PackageReference Include="Lib.Net.Http.WebPush" />
    <PackageReference Include="Serilog.Extensions.Hosting" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GarageStack.Core\GarageStack.Core.csproj" />
    <ProjectReference Include="..\GarageStack.Data\GarageStack.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GarageStack.Tests" />
  </ItemGroup>

</Project>
