blank_issues_enabled: false
contact_links:
  - name: Ask a question / General support
    url: https://github.com/joszz/garagestack/discussions
    about: For usage questions, setup help, or general discussion, please use GitHub Discussions.
